# Generated by Django 4.0.1 on 2022-01-27 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('musics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='music_file',
            field=models.FileField(null=True, upload_to='musics/', verbose_name='Music file'),
        ),
        migrations.AlterField(
            model_name='music',
            name='artist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='music_artist', to='musics.artist', verbose_name='artist'),
        ),
        migrations.AlterField(
            model_name='music',
            name='composer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='music_composer', to='musics.artist', verbose_name='composer'),
        ),
        migrations.AlterField(
            model_name='music',
            name='lyricist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='music_lyricist', to='musics.artist', verbose_name='lyricist'),
        ),
    ]
