# Generated by Django 4.0.1 on 2022-02-04 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musics', '0007_alter_music_album'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='url',
            field=models.SlugField(max_length=150, null=True, unique=True),
        ),
    ]
