# Generated by Django 4.0.1 on 2022-02-09 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musics', '0010_alter_music_album'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='music',
            name='artist',
        ),
        migrations.AddField(
            model_name='music',
            name='artist',
            field=models.ManyToManyField(null=True, related_name='musics', to='musics.Artist', verbose_name='artist'),
        ),
    ]
