# Generated by Django 4.0.1 on 2022-02-09 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musics', '0012_remove_music_artist_music_artist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='genres',
            field=models.ManyToManyField(to='musics.Genre', verbose_name='genres'),
        ),
    ]
