# Generated by Django 4.0.1 on 2022-02-24 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musics', '0015_alter_music_album'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Name')),
                ('email', models.EmailField(max_length=254)),
                ('music', models.CharField(max_length=150, verbose_name='Music title')),
                ('message', models.TextField(verbose_name='Message')),
            ],
        ),
    ]
