# Generated by Django 4.0.1 on 2022-02-24 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musics', '0016_contact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
